# Generated by Django 6.0 on 2026-01-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_module_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Capa do Curso (URL)'),
        ),
    ]
