# Generated by Django 6.0 on 2026-04-17 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_module_lesson_watchprogress_favorite'),
        ('core', '0003_alter_course_thumbnail'),
    ]

    operations = [
    ]
